# MUC Concurrent Mutations and Clinical Outcomes

### Standard imports, including CPTAC package

In [1]:
import pandas as pd
import numpy as np
import re
import scipy.stats
import statsmodels.stats.multitest
import matplotlib.pyplot as plt
import seaborn as sns
import CPTAC.Ovarian as CPTAC

Welcome to the CPTAC data service package. Available datasets may be
viewed using CPTAC.list(). In order to access a specific data set,
import a CPTAC subfolder using either 'import CPTAC.Dataset' or 'from
CPTAC import Dataset'.
******
Version: 0.2.5
******
Loading Ovarian CPTAC data:
Loading somatic_19 data...
Loading clinical data...
Loading cnv data...
Loading proteomics data...
Loading transcriptomics data...
Loading somatic_38 data...
Loading phosphoproteomics data...

 ******PLEASE READ******
CPTAC is a community resource project and data are made available
rapidly after generation for community research use. The embargo
allows exploring and utilizing the data, but the data may not be in a
publication until June 1, 2019. Please see
https://proteomics.cancer.gov/data-portal/about/data-use-agreement or
enter embargo() to open the webpage for more details.


## Set up initial dataframes and variables

In [118]:
clinical = CPTAC.get_clinical()
pd.options.display.max_columns = None
display(clinical)

Short Title        Event   Modified Time        Modified By  \
PPID                                                                     
01OV002  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV007  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV008  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV010  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV013  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV017  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV018  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV019  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV023  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV024  CPTAC-WU-01OV   Collection  7/13/2015 0:00           Guo, Lei   
01OV026  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV030  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV039  CPTAC-WU-01OV   Collection  4/25/2016 0:00   Khandekar, Divya   
01OV041  CPTAC-WU-01OV   Collection  4/22/2016 0:00   Khandekar, Divya   
01OV045  CPTAC-WU-01OV   Collection  4/25/2016 0:00   Khandekar, Divya   
01OV046  CPTAC-WU-01OV   Collection  4/28/2016 0:00   Khandekar, Divya   
01OV047  CPTAC-WU-01OV   Collection  4/28/2016 0:00   Khandekar, Divya   
01OV049  CPTAC-WU-01OV   Collection  4/28/2016 0:00   Khandekar, Divya   
02OV005  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV006  CPTAC-CS-02OV   Collection  6/17/2015 0:00   Khandekar, Divya   
02OV008  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV015  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV022  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV023  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV029  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV032  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV035  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV036  CPTAC-CS-02OV   Collection  3/21/2016 0:00   Khandekar, Divya   
02OV040  CPTAC-CS-02OV   Collection  6/23/2016 0:00   Khandekar, Divya   
02OV041  CPTAC-CS-02OV   Collection  4/21/2016 0:00   Khandekar, Divya   
...                ...          ...             ...                ...   
17OV015  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV016  CPTAC-UO-17OV   Collection   3/7/2016 0:00  Snowbarger, Carie   
17OV017  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV018  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV019  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV022  CPTAC-UO-17OV   Collection  3/21/2016 0:00  Snowbarger, Carie   
17OV025  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV026  CPTAC-UO-17OV   Collection  3/21/2016 0:00  Snowbarger, Carie   
17OV027  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV028  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV029  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV030  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV031  CPTAC-UO-17OV   Collection  3/24/2016 0:00  Snowbarger, Carie   
17OV033  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV034  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV035  CPTAC-UO-17OV   Collection  3/22/2016 0:00  Snowbarger, Carie   
17OV036  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV037  CPTAC-UO-17OV   Collection  3/22/2016 0:00  Snowbarger, Carie   
17OV038  CPTAC-UO-17OV   Collection  3/22/2016 0:00  Snowbarger, Carie   
17OV039  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
17OV040  CPTAC-UO-17OV   Collection  3/25/2016 0:00   Khandekar, Divya   
18OV001  CPTAC-

In [110]:
gene='MUC4'
clinical_outcome = 'Measure of Success of Outcome at the Completion of Initial First Course Treatment (surgery and adjuvant therapies)'
somatic = CPTAC.get_somatic_mutations()
proteomics = CPTAC.get_proteomics()
phos = CPTAC.get_phosphoproteomics()
transcriptomics = CPTAC.get_transcriptomics()
outcome = pd.DataFrame(clinical[clinical_outcome])

## MUC4 Mutations Only

In [111]:
muc4_mut_prot = CPTAC.compare_mutations(proteomics, gene)
muc4_mut_prot['Concurrent_Mutations'] = 'Single'
muc4_mut_prot.loc[muc4_mut_prot['Mutation'] == 'Wildtype_Tumor', 'Concurrent_Mutations'] = 'Wildtype'
muc4_mut_prot = muc4_mut_prot.loc[muc4_mut_prot['Mutation'] != 'Wildtype_Normal']
combined = pd.concat([outcome, muc4_mut_prot], axis=1, sort=False)
combined = combined[[clinical_outcome, 'Concurrent_Mutations']].dropna()
clinical_table = pd.crosstab(combined[clinical_outcome], combined['Concurrent_Mutations'])
print(clinical_table)
chi_test = scipy.stats.chi2_contingency(observed = clinical_table)
chi_test

Concurrent_Mutations                                Single  Wildtype
Measure of Success of Outcome at the Completion...                  
Complete Response                                       17        29
Not Reported/ Unknown                                    2         4
Partial Response                                         2         4
Progressive Disease                                      4         3
Stable Disease                                           7         6
Unknown                                                  1         0


(3.6429553957909353, 0.6018754874151304, 5, array([[19.21518987, 26.78481013],
        [ 2.50632911,  3.49367089],
        [ 2.50632911,  3.49367089],
        [ 2.92405063,  4.07594937],
        [ 5.43037975,  7.56962025],
        [ 0.41772152,  0.58227848]]))

## Combination of mutations in MUC4 and MUC17

## Find patients that have both mutations

In [112]:
second_gene = 'MUC17'
muc4_mut = CPTAC.compare_mutations(proteomics, 'CDH2', gene)
muc16_mut = CPTAC.compare_mutations(proteomics, 'CDH2', second_gene)
new_mutation = pd.DataFrame()
new_mutation[gene + ' Mutation'] = muc4_mut['Mutation']
new_mutation[second_gene + ' Mutation'] = muc16_mut['Mutation']
new_mutation['CDH2'] = muc4_mut['CDH2']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Normal']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Tumor'].loc[new_mutation[second_gene + ' Mutation'] != 'Wildtype_Tumor']
patients_both_mut_17 = new_mutation.index
patients_both_mut_17

Index(['02OV005', '02OV006', '04OV004', '04OV036', '17OV002', '17OV010',
       '17OV029', '17OV030', '17OV039'],
      dtype='object', name='patient_id')

In [113]:
muc4_mut_prot = CPTAC.compare_mutations(proteomics, gene)
muc4_mut_prot['Concurrent_Mutations'] = 'Single'
muc4_mut_prot.loc[patients_both_mut_17, 'Concurrent_Mutations'] = 'Both'
muc4_mut_prot.loc[muc4_mut_prot['Mutation'] == 'Wildtype_Tumor', 'Concurrent_Mutations'] = 'Wildtype'
muc4_mut_prot = muc4_mut_prot.loc[muc4_mut_prot['Mutation'] != 'Wildtype_Normal']
combined = pd.concat([outcome, muc4_mut_prot], axis=1, sort=False)
combined = combined[[clinical_outcome, 'Concurrent_Mutations']].dropna()
clinical_table = pd.crosstab(combined[clinical_outcome], combined['Concurrent_Mutations'])
print(clinical_table)
chi_test = scipy.stats.chi2_contingency(observed = clinical_table)
chi_test

Concurrent_Mutations                                Both  Single  Wildtype
Measure of Success of Outcome at the Completion...                        
Complete Response                                      4      13        29
Not Reported/ Unknown                                  0       2         4
Partial Response                                       1       1         4
Progressive Disease                                    2       2         3
Stable Disease                                         2       5         6
Unknown                                                0       1         0


(7.093671547594042,
 0.7165731875236268,
 10,
 array([[ 5.24050633, 13.97468354, 26.78481013],
        [ 0.6835443 ,  1.82278481,  3.49367089],
        [ 0.6835443 ,  1.82278481,  3.49367089],
        [ 0.79746835,  2.12658228,  4.07594937],
        [ 1.48101266,  3.94936709,  7.56962025],
        [ 0.11392405,  0.30379747,  0.58227848]]))

## MUC16 results

## Find patients that have both mutations

In [114]:
second_gene = 'MUC16'
muc4_mut = CPTAC.compare_mutations(proteomics, 'CDH2', gene)
muc16_mut = CPTAC.compare_mutations(proteomics, 'CDH2', second_gene)
new_mutation = pd.DataFrame()
new_mutation[gene + ' Mutation'] = muc4_mut['Mutation']
new_mutation[second_gene + ' Mutation'] = muc16_mut['Mutation']
new_mutation['CDH2'] = muc4_mut['CDH2']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Normal']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Tumor'].loc[new_mutation[second_gene + ' Mutation'] != 'Wildtype_Tumor']
patients_both_mut_16 = new_mutation.index
patients_both_mut_16

Index(['02OV005', '04OV011', '04OV036', '04OV037', '14OV011', '17OV001',
       '17OV002', '17OV011', '26OV009'],
      dtype='object', name='patient_id')

In [115]:
muc4_mut_prot = CPTAC.compare_mutations(proteomics, gene)
muc4_mut_prot['Concurrent_Mutations'] = 'Single'
muc4_mut_prot.loc[patients_both_mut_16, 'Concurrent_Mutations'] = 'Both'
muc4_mut_prot.loc[muc4_mut_prot['Mutation'] == 'Wildtype_Tumor', 'Concurrent_Mutations'] = 'Wildtype'
muc4_mut_prot = muc4_mut_prot.loc[muc4_mut_prot['Mutation'] != 'Wildtype_Normal']
combined = pd.concat([outcome, muc4_mut_prot], axis=1, sort=False)
combined = combined[[clinical_outcome, 'Concurrent_Mutations']].dropna()
clinical_table = pd.crosstab(combined[clinical_outcome], combined['Concurrent_Mutations'])
print(clinical_table)
chi_test = scipy.stats.chi2_contingency(observed = clinical_table)
chi_test

Concurrent_Mutations                                Both  Single  Wildtype
Measure of Success of Outcome at the Completion...                        
Complete Response                                      6      11        29
Not Reported/ Unknown                                  0       2         4
Partial Response                                       0       2         4
Progressive Disease                                    1       3         3
Stable Disease                                         1       6         6
Unknown                                                1       0         0


(12.49319664005392,
 0.2534030840551113,
 10,
 array([[ 5.24050633, 13.97468354, 26.78481013],
        [ 0.6835443 ,  1.82278481,  3.49367089],
        [ 0.6835443 ,  1.82278481,  3.49367089],
        [ 0.79746835,  2.12658228,  4.07594937],
        [ 1.48101266,  3.94936709,  7.56962025],
        [ 0.11392405,  0.30379747,  0.58227848]]))

## All three mutations

In [116]:
second_gene = 'MUC16'
third_gene = 'MUC17'
muc4_mut = CPTAC.compare_mutations(proteomics, 'CDH2', gene)
muc16_mut = CPTAC.compare_mutations(proteomics, 'CDH2', second_gene)
muc17_mut = CPTAC.compare_mutations(proteomics, 'CDH2', third_gene)
new_mutation = pd.DataFrame()
new_mutation[gene + ' Mutation'] = muc4_mut['Mutation']
new_mutation[second_gene + ' Mutation'] = muc16_mut['Mutation']
new_mutation[third_gene + ' Mutation'] = muc17_mut['Mutation']
new_mutation['CDH2'] = muc4_mut['CDH2']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Normal']
new_mutation = new_mutation.loc[new_mutation[gene + ' Mutation'] != 'Wildtype_Tumor'].loc[new_mutation[second_gene + ' Mutation'] != 'Wildtype_Tumor'].loc[new_mutation[third_gene + ' Mutation'] != 'Wildtype_Tumor']
patients_all_mut = new_mutation.index
patients_all_mut

Index(['02OV005', '04OV036', '17OV002'], dtype='object', name='patient_id')

In [117]:
muc4_mut_prot = CPTAC.compare_mutations(proteomics, gene)
muc4_mut_prot['Concurrent_Mutations'] = 'Single'
muc4_mut_prot.loc[patients_all_mut, 'Concurrent_Mutations'] = 'All'
muc4_mut_prot.loc[muc4_mut_prot['Mutation'] == 'Wildtype_Tumor', 'Concurrent_Mutations'] = 'Wildtype'
muc4_mut_prot = muc4_mut_prot.loc[muc4_mut_prot['Mutation'] != 'Wildtype_Normal']
combined = pd.concat([outcome, muc4_mut_prot], axis=1, sort=False)
combined = combined[[clinical_outcome, 'Concurrent_Mutations']].dropna()
clinical_table = pd.crosstab(combined[clinical_outcome], combined['Concurrent_Mutations'])
print(clinical_table)
chi_test = scipy.stats.chi2_contingency(observed = clinical_table)
chi_test

Concurrent_Mutations                                All  Single  Wildtype
Measure of Success of Outcome at the Completion...                       
Complete Response                                     3      14        29
Not Reported/ Unknown                                 0       2         4
Partial Response                                      0       2         4
Progressive Disease                                   0       4         3
Stable Disease                                        0       7         6
Unknown                                               0       1         0


(6.983337718781954,
 0.7270170333597092,
 10,
 array([[ 1.74683544, 17.46835443, 26.78481013],
        [ 0.2278481 ,  2.27848101,  3.49367089],
        [ 0.2278481 ,  2.27848101,  3.49367089],
        [ 0.26582278,  2.65822785,  4.07594937],
        [ 0.49367089,  4.93670886,  7.56962025],
        [ 0.03797468,  0.37974684,  0.58227848]]))